# Generated by Django 2.1.2 on 2018-10-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20181019_2051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='name',
        ),
        migrations.AddField(
            model_name='widget',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='widget',
            name='description',
            field=models.CharField(max_length=500),
        ),
    ]
